/*
 * Software Engineering Project Juggernaut
 * Jaehwan Lee
 * Sujeong Kim
 */
package cse.se.juggernaut;

public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        System.out.println("Interface Initialized");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        IconRedraw = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        IconNewDSM = new javax.swing.JButton();
        IconOpenDSM = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        IconSaveDSM = new javax.swing.JButton();
        IconSaveDSMAs = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        IconNewClustering = new javax.swing.JButton();
        IconLoadClustering = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        IconSaveClustering = new javax.swing.JButton();
        IconSaveClusteringAs = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        IconNewDSMRow = new javax.swing.JButton();
        IconRename = new javax.swing.JButton();
        IconDelete = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        IconExpandAll = new javax.swing.JButton();
        IconCollapseAll = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        IconGroup = new javax.swing.JButton();
        IconUngroup = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        IconMoveUp = new javax.swing.JButton();
        IconMoveDown = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        IconSort = new javax.swing.JButton();
        IconPartition = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        moduleTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        ItemNewDSM = new javax.swing.JMenuItem();
        ItemOpenDSM = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ItemSaveDSM = new javax.swing.JMenuItem();
        ItemSaveDSMAs = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ItemNewClustering = new javax.swing.JMenuItem();
        ItemLoadClustering = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ItemSaveClustering = new javax.swing.JMenuItem();
        ItemSaveClusteringAs = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        ItemExit = new javax.swing.JMenuItem();
        MenuMetrics = new javax.swing.JMenu();
        ItemPropagationCost = new javax.swing.JMenuItem();
        MenuView = new javax.swing.JMenu();
        ItemRedraw = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        ItemFind = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        ItemShowRowLabels = new javax.swing.JCheckBoxMenuItem();
        ItemShowDepStr = new javax.swing.JCheckBoxMenuItem();
        MenuHelp = new javax.swing.JMenu();
        ItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setFloatable(false);
        jToolBar2.setMinimumSize(new java.awt.Dimension(600, 23));

        IconRedraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/redraw.png"))); // NOI18N
        IconRedraw.setToolTipText("Redraw");
        IconRedraw.setFocusable(false);
        IconRedraw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconRedraw.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IconRedraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IconRedrawActionPerformed(evt);
            }
        });
        jToolBar2.add(IconRedraw);
        jToolBar2.add(jSeparator11);

        IconNewDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/new-dsm.png"))); // NOI18N
        IconNewDSM.setToolTipText("New DSM");
        IconNewDSM.setFocusable(false);
        IconNewDSM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconNewDSM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconNewDSM);

        IconOpenDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/open-dsm.png"))); // NOI18N
        IconOpenDSM.setToolTipText("Open DSM");
        IconOpenDSM.setFocusable(false);
        IconOpenDSM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconOpenDSM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconOpenDSM);
        jToolBar2.add(jSeparator1);

        IconSaveDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx.png"))); // NOI18N
        IconSaveDSM.setToolTipText("Save DSM");
        IconSaveDSM.setFocusable(false);
        IconSaveDSM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSaveDSM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconSaveDSM);

        IconSaveDSMAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx-as.png"))); // NOI18N
        IconSaveDSMAs.setToolTipText("Save DSM As...");
        IconSaveDSMAs.setFocusable(false);
        IconSaveDSMAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSaveDSMAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconSaveDSMAs);
        jToolBar2.add(jSeparator12);

        IconNewClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/new-clsx.png"))); // NOI18N
        IconNewClustering.setToolTipText("New Clustering");
        IconNewClustering.setFocusable(false);
        IconNewClustering.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconNewClustering.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconNewClustering);

        IconLoadClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/open-clsx.png"))); // NOI18N
        IconLoadClustering.setToolTipText("Load CLustering");
        IconLoadClustering.setFocusable(false);
        IconLoadClustering.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconLoadClustering.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconLoadClustering);
        jToolBar2.add(jSeparator13);

        IconSaveClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx.png"))); // NOI18N
        IconSaveClustering.setToolTipText("Save Clustering");
        IconSaveClustering.setFocusable(false);
        IconSaveClustering.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSaveClustering.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconSaveClustering);

        IconSaveClusteringAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx-as.png"))); // NOI18N
        IconSaveClusteringAs.setToolTipText("Save Clustering As...");
        IconSaveClusteringAs.setFocusable(false);
        IconSaveClusteringAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSaveClusteringAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(IconSaveClusteringAs);

        jPanel1.setMinimumSize(new java.awt.Dimension(265, 0));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setMinimumSize(new java.awt.Dimension(265, 25));

        IconNewDSMRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/new-row.png"))); // NOI18N
        IconNewDSMRow.setToolTipText("New DSM Row");
        IconNewDSMRow.setFocusable(false);
        IconNewDSMRow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconNewDSMRow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IconNewDSMRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IconNewDSMRowActionPerformed(evt);
            }
        });
        jToolBar1.add(IconNewDSMRow);

        IconRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/rename.png"))); // NOI18N
        IconRename.setToolTipText("Rename");
        IconRename.setFocusable(false);
        IconRename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconRename.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconRename);

        IconDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/delete.png"))); // NOI18N
        IconDelete.setToolTipText("Delete");
        IconDelete.setFocusable(false);
        IconDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconDelete);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.add(jSeparator14);

        IconExpandAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/expand.png"))); // NOI18N
        IconExpandAll.setToolTipText("Expand All");
        IconExpandAll.setFocusable(false);
        IconExpandAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconExpandAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconExpandAll);

        IconCollapseAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/collapse.png"))); // NOI18N
        IconCollapseAll.setToolTipText("Collapse All");
        IconCollapseAll.setFocusable(false);
        IconCollapseAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconCollapseAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconCollapseAll);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.add(jSeparator8);

        IconGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/group.png"))); // NOI18N
        IconGroup.setToolTipText("Group");
        IconGroup.setFocusable(false);
        IconGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconGroup);

        IconUngroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/ungroup.png"))); // NOI18N
        IconUngroup.setToolTipText("Ungroup");
        IconUngroup.setFocusable(false);
        IconUngroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconUngroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconUngroup);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.add(jSeparator9);

        IconMoveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/up.png"))); // NOI18N
        IconMoveUp.setToolTipText("Move Up");
        IconMoveUp.setFocusable(false);
        IconMoveUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconMoveUp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconMoveUp);

        IconMoveDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/down.png"))); // NOI18N
        IconMoveDown.setToolTipText("Move Down");
        IconMoveDown.setFocusable(false);
        IconMoveDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconMoveDown.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconMoveDown);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.add(jSeparator10);

        IconSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/sort.png"))); // NOI18N
        IconSort.setToolTipText("Sort");
        IconSort.setFocusable(false);
        IconSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(IconSort);

        IconPartition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/partition.png"))); // NOI18N
        IconPartition.setToolTipText("Partition");
        IconPartition.setFocusable(false);
        IconPartition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconPartition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IconPartition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IconPartitionActionPerformed(evt);
            }
        });
        jToolBar1.add(IconPartition);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(252, 23));

        moduleTree.setMaximumSize(new java.awt.Dimension(2048, 64));
        moduleTree.setMinimumSize(new java.awt.Dimension(265, 0));
        moduleTree.setPreferredSize(new java.awt.Dimension(200, 64));
        jScrollPane1.setViewportView(moduleTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        MenuFile.setText("File");

        ItemNewDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/new-dsm.png"))); // NOI18N
        ItemNewDSM.setText("New DSM");
        MenuFile.add(ItemNewDSM);

        ItemOpenDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/open-dsm.png"))); // NOI18N
        ItemOpenDSM.setText("Open DSM...");
        MenuFile.add(ItemOpenDSM);
        MenuFile.add(jSeparator2);

        ItemSaveDSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx.png"))); // NOI18N
        ItemSaveDSM.setText("Save DSM");
        ItemSaveDSM.setEnabled(false);
        ItemSaveDSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSaveDSMActionPerformed(evt);
            }
        });
        MenuFile.add(ItemSaveDSM);

        ItemSaveDSMAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx-as.png"))); // NOI18N
        ItemSaveDSMAs.setText("Save DSM As...");
        ItemSaveDSMAs.setEnabled(false);
        MenuFile.add(ItemSaveDSMAs);
        MenuFile.add(jSeparator3);

        ItemNewClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/new-clsx.png"))); // NOI18N
        ItemNewClustering.setText("New Clustering");
        MenuFile.add(ItemNewClustering);

        ItemLoadClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/open-clsx.png"))); // NOI18N
        ItemLoadClustering.setText("Load Clustering ...");
        MenuFile.add(ItemLoadClustering);
        MenuFile.add(jSeparator4);

        ItemSaveClustering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx.png"))); // NOI18N
        ItemSaveClustering.setText("Save Clustering");
        ItemSaveClustering.setEnabled(false);
        MenuFile.add(ItemSaveClustering);

        ItemSaveClusteringAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/save-clsx-as.png"))); // NOI18N
        ItemSaveClusteringAs.setText("Save Clustering As...");
        ItemSaveClusteringAs.setEnabled(false);
        MenuFile.add(ItemSaveClusteringAs);
        MenuFile.add(jSeparator5);

        ItemExit.setText("Exit");
        MenuFile.add(ItemExit);

        jMenuBar1.add(MenuFile);

        MenuMetrics.setText("Metrics");

        ItemPropagationCost.setText("Propagation Cost");
        ItemPropagationCost.setEnabled(false);
        ItemPropagationCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemPropagationCostActionPerformed(evt);
            }
        });
        MenuMetrics.add(ItemPropagationCost);

        jMenuBar1.add(MenuMetrics);

        MenuView.setText("View");

        ItemRedraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/se/juggernaut/icons/redraw.png"))); // NOI18N
        ItemRedraw.setText("Redraw");
        ItemRedraw.setEnabled(false);
        MenuView.add(ItemRedraw);
        MenuView.add(jSeparator6);

        ItemFind.setText("Find");
        ItemFind.setEnabled(false);
        MenuView.add(ItemFind);
        MenuView.add(jSeparator7);

        ItemShowRowLabels.setText("Show Row Labels");
        MenuView.add(ItemShowRowLabels);

        ItemShowDepStr.setText("jCheckBoxMenuItem1");
        ItemShowDepStr.setEnabled(false);
        MenuView.add(ItemShowDepStr);

        jMenuBar1.add(MenuView);

        MenuHelp.setText("Help");

        ItemAbout.setText("Help");
        MenuHelp.add(ItemAbout);

        jMenuBar1.add(MenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        jToolBar2.setFloatable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconRedrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IconRedrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IconRedrawActionPerformed

    private void ItemSaveDSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSaveDSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemSaveDSMActionPerformed

    private void ItemPropagationCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPropagationCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemPropagationCostActionPerformed

    private void IconNewDSMRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IconNewDSMRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IconNewDSMRowActionPerformed

    private void IconPartitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IconPartitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IconPartitionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IconCollapseAll;
    private javax.swing.JButton IconDelete;
    private javax.swing.JButton IconExpandAll;
    private javax.swing.JButton IconGroup;
    private javax.swing.JButton IconLoadClustering;
    private javax.swing.JButton IconMoveDown;
    private javax.swing.JButton IconMoveUp;
    private javax.swing.JButton IconNewClustering;
    private javax.swing.JButton IconNewDSM;
    private javax.swing.JButton IconNewDSMRow;
    private javax.swing.JButton IconOpenDSM;
    private javax.swing.JButton IconPartition;
    private javax.swing.JButton IconRedraw;
    private javax.swing.JButton IconRename;
    private javax.swing.JButton IconSaveClustering;
    private javax.swing.JButton IconSaveClusteringAs;
    private javax.swing.JButton IconSaveDSM;
    private javax.swing.JButton IconSaveDSMAs;
    private javax.swing.JButton IconSort;
    private javax.swing.JButton IconUngroup;
    private javax.swing.JMenuItem ItemAbout;
    private javax.swing.JMenuItem ItemExit;
    private javax.swing.JMenuItem ItemFind;
    private javax.swing.JMenuItem ItemLoadClustering;
    private javax.swing.JMenuItem ItemNewClustering;
    private javax.swing.JMenuItem ItemNewDSM;
    private javax.swing.JMenuItem ItemOpenDSM;
    private javax.swing.JMenuItem ItemPropagationCost;
    private javax.swing.JMenuItem ItemRedraw;
    private javax.swing.JMenuItem ItemSaveClustering;
    private javax.swing.JMenuItem ItemSaveClusteringAs;
    private javax.swing.JMenuItem ItemSaveDSM;
    private javax.swing.JMenuItem ItemSaveDSMAs;
    private javax.swing.JCheckBoxMenuItem ItemShowDepStr;
    private javax.swing.JCheckBoxMenuItem ItemShowRowLabels;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenu MenuMetrics;
    private javax.swing.JMenu MenuView;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree moduleTree;
    // End of variables declaration//GEN-END:variables
}
